name: dsci310_project_08
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - jupyterlab=4.5.4      
  - ipykernel=7.2.0       
  - pandas=3.0.0
  - scikit-learn=1.8.0
  - matplotlib=3.10.8 
  - seaborn=0.13.2
  - numpy=2.4.2